jobs:

  good-to-merge:

    name: Good To Merge

    description: |
      This job depends on all other tests and checks
      and it will pass if and only if all dependencies have passed.
      It also include *git* meta checks (only relevant for pushing to master).
      Status of this job is **used by github's "branch protection"**!

    depends_on:
      meta passed:
        type: job
        job_key: meta
        states: [passed]
      all tests passed:
        type: job
        job_key: all-tests
        states: [passed]

    context:
      task_defaults:
        max_trials: 1
      tasks:
        include:
          - path: cider-ci/context-components/merged-submodules-check.yml
