jobs:

  manage_unstable_scenarios:

    name: 'Manage: Unstable Scenarios'

    description: |
      Run Manage unstable scenarios

    priority: -5

    run_when:
      branch name matches master or manage:
        type: branch
        include_match: '^.*(master|manage).*$'
        exclude_match: '^.*(no-ci|hotspot).*$'

    context:

      task_defaults:
        load: 1.5
        max_trials: 25
        eager_trials: 1
        include:
          - cider-ci/task_components/database.yml

      include:
        - cider-ci/shared/main_context.yml
        - cider-ci/tasks/manage_unstable_scenarios.yml
